name: Block Direct Push to Staging

on:
  push:
    branches: [staging]

jobs:
  check-merge-from-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: |
          git fetch origin main
          git fetch origin staging

      - name: Check for direct push
        run: |
          STAGING_HEAD=$(git rev-parse HEAD)
          MAIN_HEAD=$(git rev-parse origin/main)
          
          # Get all commits in staging that are not in main
          STAGING_ONLY=$(git rev-list origin/main..HEAD)
          
          if [ -z "$STAGING_ONLY" ]; then
            echo "✅ Staging is up to date with main (no new commits)"
            exit 0
          fi
          
          # Check each commit that's only in staging
          for commit in $STAGING_ONLY; do
            PARENT_COUNT=$(git rev-list --parents -n 1 $commit | awk '{print NF-1}')
            
            # If it's a merge commit, check if it merges from main
            if [ "$PARENT_COUNT" -eq 2 ]; then
              PARENT1=$(git rev-parse ${commit}^1)
              PARENT2=$(git rev-parse ${commit}^2)
              
              # Check if second parent is from main branch
              if git merge-base --is-ancestor $PARENT2 origin/main && \
                 git merge-base --is-ancestor origin/main $PARENT2; then
                echo "✅ Commit $commit is a valid merge from main"
                continue
              fi
            fi
            
            # If we get here, this commit is not a merge from main
            echo "❌ Direct push to staging blocked!"
            echo ""
            echo "Commit $commit was pushed directly to staging."
            echo ""
            echo "Allowed workflow:"
            echo "1. Push changes to main (or create PR to main)"
            echo "2. Merge main into staging"
            echo ""
            echo "Direct pushes to staging are not allowed for code quality control."
            exit 1
          done
          
          echo "✅ All commits on staging are valid merges from main"
          exit 0