name: Block Direct Push to Staging

on:
  push:
    branches: [staging]

jobs:
  check-merge-from-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: |
          git fetch origin main
          git fetch origin staging

      - name: Check for direct push
        run: |
          MAIN_HEAD=$(git rev-parse origin/main)
          STAGING_HEAD=$(git rev-parse HEAD)
          
          # Find the common ancestor
          BASE=$(git merge-base origin/main HEAD)
          
          # Get commits that are in staging but not in main
          STAGING_ONLY_COMMITS=$(git rev-list --count $BASE..$STAGING_HEAD)
          
          if [ "$STAGING_ONLY_COMMITS" -eq 0 ]; then
            echo "✅ No direct push detected - staging is aligned with main"
            exit 0
          fi
          
          # Count commits in main that are not in staging
          MAIN_ONLY_COMMITS=$(git rev-list --count $BASE..$MAIN_HEAD)
          
          if [ "$MAIN_ONLY_COMMITS" -gt 0 ]; then
            echo "✅ Staging is being updated from main"
            echo "main has $MAIN_ONLY_COMMITS commit(s) that will be merged into staging"
            exit 0
          fi
          
          # If we get here, staging has commits that main doesn't have
          echo "❌ Direct push to staging blocked!"
          echo ""
          echo "Staging has $STAGING_ONLY_COMMITS commit(s) that don't exist in main."
          echo ""
          echo "Allowed workflow:"
          echo "1. Push changes to main (or create PR to main)"
          echo "2. Merge main into staging"
          echo ""
          echo "Direct pushes to staging are not allowed for code quality control."
          exit 1


