name: Keep Supabase Active

on:
  schedule:
    # Run every day at 6:00 AM UTC (every ~24 hours, well before 7-day pause)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase Active
        run: |
          # Only run on staging branch (or scheduled/manual triggers)
          if [ "${{ github.ref }}" != "refs/heads/staging" ] && [ "${{ github.event_name }}" != "schedule" ] && [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            exit 0
          fi
          
          API_URL="${{ secrets.API_URL }}"
          
          if [ -z "$API_URL" ]; then
            echo "Error: API_URL secret is not set"
            exit 1
          fi
          
          echo "DEBUG: API_URL is set"
          echo "DEBUG: Making request to: ${API_URL}/health"
          
          # Get verbose output to see what's happening
          HEALTH_RESPONSE=$(curl -v -s -w "\nHTTP_CODE:%{http_code}\n" "${API_URL}/health" 2>&1 || echo -e "\nHTTP_CODE:000")
          
          echo "DEBUG: Full curl response:"
          echo "$HEALTH_RESPONSE"
          echo "---"
          
          HEALTH_STATUS=$(echo "$HEALTH_RESPONSE" | grep -o "HTTP_CODE:[0-9]*" | cut -d: -f2 || echo "000")
          
          echo "DEBUG: Extracted status code: ${HEALTH_STATUS}"
          
          if [ "$HEALTH_STATUS" -eq 200 ]; then
            exit 0
          else
            echo "Health check failed with status code: ${HEALTH_STATUS}"
            exit 1
          fi

