name: Keep Supabase Active

on:
  schedule:
    # Run every day at 6:00 AM UTC (every ~24 hours, well before 7-day pause)
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual trigger for testing

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase Active
        run: |
          # Only run on staging branch (or scheduled/manual triggers)
          if [ "${{ github.ref }}" != "refs/heads/staging" ] && [ "${{ github.event_name }}" != "schedule" ] && [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            exit 0
          fi
          
          API_URL="${{ secrets.API_URL }}"
          
          if [ -z "$API_URL" ]; then
            echo "Error: API_URL secret is not set"
            exit 1
          fi
          
          HEALTH_RESPONSE=$(curl -s -w "\n%{http_code}" "${API_URL}/health" 2>&1 || echo -e "\n000")
          HEALTH_STATUS=$(echo "$HEALTH_RESPONSE" | tail -n1)
          
          if [ "$HEALTH_STATUS" -eq 200 ]; then
            exit 0
          else
            echo "Health check failed with status code: ${HEALTH_STATUS}"
            exit 1
          fi

